# 1.2 ¿El cálculo de probabilidades es una parte de la estadística? {#Probabilidad .unnumbered}

La teoría de la probabilidad y el cálculo de probabilidades son una parte de las matemáticas. Una parte que puede resultar muy útil en el marco de un análisis estadístico, pero no creemos que deba considerarse parte de la estadística.

En los problemas de cálculo de probabilidades se suponen conocidas las características de la población (que en muchos casos es una población teórica) y nos preguntamos por las características de una muestra obtenida de esa población. Ejemplos típicos de problemas de cálculo de probabilidades son:

-   ¿Cuál es la probabilidad de que realizando una apuesta nos toque el primer premio de la lotería primitiva (una lotería tipo 6/49)?

-   Si una máquina fabrica un 3% de piezas defectuosas ¿Cuál es la probabilidad de que en un lote de 30 piezas haya alguna defectuosa?

En estadística nos ocupamos justo de lo contrario. Conocemos las características de una muestra que consideramos representativa de su población y lo que interesa es estimar (“hacernos una idea de”) las características de esa población. Ni que decir tiene que la muestra no vine dada y hay que pensar en la mejor manera de elegirla con los recursos disponibles. Después habrá que analizar los valores obtenidos para realizar las estimaciones. Todo esto, desde plantear claramente las preguntas que se desea responder hasta explicar las conclusiones a que se ha llegado, está lleno de dificultades que no tienen nada que ver con el cálculo de probabilidades. Problemas de estadística serían:

-   Con base en los resultados de un sondeo electoral, estimar el número de escaños que obtendrá un partido en las próximas elecciones.

-   A partir de los resultados de un estudio clínico, determinar si un nuevo medicamento es más eficaz que el usado habitualmente.

Claro que nuestras estimaciones o nuestras conclusiones nunca son apuestas seguras y ahí es donde aparece el lenguaje de la probabilidad: Informamos sobre la probabilidad de que el número de escaños se encuentre entre determinados valores, o afirmamos que con una determinada probabilidad de error (que se fija de antemano y que se designa “nivel de significación”) puede decirse que el nuevo medicamento es eficaz. Pero, en general, el uso que hacemos de la probabilidad no requiere saber resolver problemas complicados de combinatoria o de cálculo de probabilidades. Basta con unas reglas bastante sencillas y al alcance de todos.
