# 1.3 ¿Qué es la estadística? {#QueEs .unnumbered}

Existen muchas definiciones de lo que es la estadística. En el ámbito académico, una de las más cortas y acertadas nos la dio un estudiante cuando discutíamos este tema el primer día de clase: "La estadística es una asignatura". Desde luego, tenía razón.

Seguramente la estadística es la asignatura que aparece en los planes de estudios de más titulaciones, pero no podemos decir que sea la más apreciada. Muchos estudiantes la consideran una asignatura más bien antipática, en la que se realizan consideraciones ininteligibles que poco o nada tienen que ver con su vocación y sus intereses. Quizá por eso, una vez superada, se produce un cierto desapego y la estadística se queda en eso, en una asignatura.

Y, por si esto fuera poco, en las antípodas de la visión formal y académica, existe también una visión un tanto despectiva en la que la estadística se relaciona con porcentajes tendenciosos, con gráficos manipulados y con números que siempre hay manera de presentar de la forma que convenga y, claro, unas técnicas que sirven lo mismo para justificar que algo es blanco como que es negro, no son nada fiables para saber de que color son las cosas.

### Un poco de historia

La estadística como "cuentas del Estado" --de ahí su nombre-- surgió cuando los gobernantes necesitaron conocer cuantas personas vivían en sus dominios, el volumen de las cosechas o los impuestos que cada familia debía pagar, y de eso hace ya miles de años. Esto significaba recoger datos y ordenarlos, tabularlos y quizá realizar algunos cálculos que estarían dentro de lo que hoy denominamos "estadística descriptiva". Esto fue la estadística hasta los inicios del siglo XX, hace cuatro días.

Con unas motivaciones totalmente distintas --en este caso relacionadas con la búsqueda de estrategias en los juegos de azar--, en el siglo XVII se empezó a estudiar seriamente ("matemáticamente") el cálculo de probabilidades. Más tarde, la estadística clásica encontró en las probabilidades el lenguaje y las herramientas que le permitían hacer estimaciones sobre la población conociendo solo una parte e informando sobre el grado de incertidumbre de sus conclusiones. Esto aumentó enormemente sus posibilidades y su campo de actuación.

La estadística que se explica en los cursos introductorios se creó, fundamentalmente, en la primera mitad del siglo XX. Al inicio de esta nueva época los métodos estadísticos se desarrollaron en torno a aplicaciones concretas (seguros de vida, ciencias naturales, industria, agricultura...) pero el interés por crear nuevos métodos para el análisis de los datos (¡estaba todo por hacer!) se despegó de las aplicaciones prácticas, especialmente en el ámbito académico, y se empezaron a crear desarrollos matemáticos que poco o nada tenían que ver con el estudio de la realidad que nos rodea. Esta irrupción de las matemáticas en la estadística también ha tenido repercusiones en la docencia. Muchas veces los profesores de estadística son y actúan como profesores de matemáticas, lo cual seguramente tiene bastante que ver con las causas del desafecto por la asignatura en aquellos estudiantes para los cuales su vocación es otra.

### Estadística y adquisición de conocimiento

Mejoramos nuestro conocimiento a base de plantearnos preguntas e intentar responderlas. La estadística juega un papel protagonista cuando para responder a esas preguntas se necesitan datos. Ejemplos de preguntas podrían ser:

::: lista-compacta
-   Biología: ¿Cómo evoluciona el número de ejemplares de cierto tipo de ave en un territorio?
-   Medicina: ¿Es eficaz una nueva vacuna?
-   Medio ambiente: ¿Qué porcentaje de plástico se recicla?
-   Economía: ¿Cuánto están subiendo los precios?
-   Ingeniería: ¿Qué catalizador aumenta más el rendimiento de una reacción química?
-   Marketing: ¿Qué tipo de envoltorio logra mayores ventas?
-   Previsiones: ¿Cuánta electricidad se consumirá mañana?
:::

La estadística trata de cómo recoger y de cómo analizar los datos para responder a las preguntas planteadas. Raramente se consiguen todos los datos que nos gustaría tener, y menos todavía con las características deseadas, pero la estadística tiene herramientas para enfrentarse a estas situaciones y sacar el máximo provecho de los recursos disponibles, todo esto, como ya sabemos, con una medida conocida de la confianza con que podemos ofrecer nuestras conclusiones.

La estadística está muy relacionada con el método científico, que se basa en la observación, medición, experimentación, planteamiento y contraste de las hipótesis con datos experimentales... También cabe poner de manifiesto que el "elemento desencadenante", lo que pone en marcha el proceso, es la pregunta que nos planteamos. No nos gusta analizar datos "para ver lo que sale", siempre buscamos algo y saber lo que se busca --hacerse la pregunta adecuada-- también es importante. Obtener los datos necesarios suele ser la parte más delicada y laboriosa. Una vez se tienen los datos, muchas veces las preguntas se pueden responder con análisis gráficos sencillos, aunque en otros casos hay que recurrir a técnicas más sofisticadas.

### Nuestra definición

La estadística es la disciplina que trata de la recogida y el análisis de datos para responder a las preguntas que nos planteamos en el proceso de adquisición de nuevos conocimientos, en un contexto en el que casi siempre están presentes la variabilidad y la incertidumbre.
