# 1.4 ¿Qué es la ciencia de datos (o *Data Science*)? {#DataScience .unnumbered}

El mantra que tanto hemos repetido en las clases de Estadística de que "los datos son siempre un recurso escaso" dejó de ser cierto en muchos casos, aunque en muchos otros --en los sondeos electorales, sin ir más lejos-- sigue siendo tan válido como siempre.

Cada vez es más habitual capturar datos y enviarlos automáticamente a esa nube que parece no tener límites. Por ejemplo, las grandes instalaciones de aire acondicionado pueden colocar sensores que captan la presión del aire o las vibraciones en puntos clave de las máquinas y envían a la nube esos valores, que pueden ser recuperados y analizados desde cualquier lugar. Es también muy típico el ejemplo de los supermercados, que pueden almacenar la información de lo que ha comprado cada uno de sus clientes, pudiendo realizar también un seguimiento detallado de la evolución de las compras de los que tienen tarjeta de fidelidad.

Una vez que somos capaces de almacenar tantos datos, lo siguiente es intentar sacar provecho de ellos. ¿Cuándo conviene cambiar los filtros o sustituir una pieza que está a punto de romperse? ¿Qué oferta conviene realizar a determinado tipo de clientes? En muchos casos basta con aplicar técnicas clásicas de análisis exploratorio de datos o con la construcción de modelos conceptualmente muy sencillos, pero en otros es necesario utilizar técnicas más sofisticadas y, en todos los casos, el manejo y la gestión de grandes volúmenes de datos entraña unas dificultades específicas.

Básicamente, lo que se ha dado en llamar “Ciencia de Datos” es un conjunto de conocimientos relacionados con la captación, almacenamiento y análisis de datos para crear algoritmos que permitan identificar patrones, casi siempre con el objetivo de hacer previsiones. Algunos de estos algoritmos son capaces de reajustarse automáticamente aprendiendo de sus errores (*machine learning*). En terrenos como la identificación de imágenes (reconocimiento facial) o de sonidos (“Alexa, ¿qué hora es?”), estos métodos son excelentes. También en otros casos, como la previsión de valores que evolucionan en el tiempo, el uso de unos algoritmos llamados redes neuronales suele ofrecer mejores resultados que los métodos clásicos.

También es verdad que no es oro todo lo que reluce. Seguramente algunas de sus posibilidades han sido sobrevaloradas por empresas consultoras que ven en estas técnicas con nombre sugerente (*machine learning*, *deep learning*…) la posibilidad de vender nuevos productos.

Una peculiaridad de esos algoritmos es que actúan como ``cajas negras'' en las que se tienen unas variables de entrada $X$, y otras de salida $Y$, y lo que se pretende es obtener buenas previsiones de los valores de $Y$, dado un conjunto de valores de $X$, pero sin llegar a entender cómo esos valores de $X$ están afectando a los de $Y$. El hecho de no conocer las relaciones causa-efecto limita sus posibilidades en la solución de problemas cuando es necesario conocer cuales son las causas que los provocan para poder plantear soluciones eficaces. Por otra parte, el esfuerzo que se realiza intentando obtener información de grandes volúmenes de datos de dudosa calidad (muchas veces misión imposible) sería mejor reorientarlo a plantearse qué datos se necesitan y planificar su recogida con el rigor y la estructura adecuadas para que de manera transparente y fiable se pueda obtener la información deseada así como un mejor conocimiento del proceso en estudio.

Es un tema controvertido si la "Ciencia de Datos" debe ser considerada una parte de la estadística o si se trata de una nueva disciplina. Nuestra opinión es que depende de lo que entendamos por estadística. Si la estadística es la parte de las matemáticas que se dedica a crear métodos estadísticos, entonces realmente la ciencia de datos es una nueva disciplina, mucho más orientada a la resolución de problemas prácticos. Si, tal como nosotros pensamos, la estadística es la disciplina que trata de la recogida y el análisis de datos para responder a las preguntas que nos planteamos, no hay ninguna duda de que la ciencia de datos encaja perfectamente en esa definición.

En cualquier caso, entender el funcionamiento de esos algoritmos, ser capaces de programar y de interactuar con grandes volúmenes de datos, así como conocer las posibilidades de almacenamiento y computación en la nube son habilidades muy demandadas y con un gran futuro.
