# 2.2 ¿Tiene alguna aplicación práctica la media geométrica? {#geometrica .unnumbered}

Sí la tiene, aunque muchas menos que la media aritmética. Un caso típico de uso de la media geométrica lo tenemos en el cálculo del valor medio de una tasa de crecimiento. Si una población tenía 10.000 habitantes en el año cero, creció el primer año a una tasa del 5 %, el segundo a una tasa del 20 % y el tercero al 50 % ¿A qué tasa promedio ha crecido durante estos tres años?


```{=html}
<div class="tabla-wrapper2">

<table class="tabla-0202">
  <thead>
    <tr>
      <th style="vertical-align: middle;">Año</th>
      <th>Poblacion <br> inicial</th>
      <th>Tasa de <br> crecimiento</th>
      <th>Factor de <br> expansión</th>
      <th>Población al <br> final del año</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td> <td>10.000</td> <td>0,05</td> <td>1,05</td> <td>10.500</td>
    </tr>
    <tr>
      <td>2</td> <td>10.500</td> <td>0,20</td> <td>1,20</td> <td>12.600</td>
    </tr>
    <tr>
      <td>3</td> <td>12.600</td> <td>0,50</td> <td>1,50</td> <td>18.900</td>
    </tr>
  </tbody>
</table>
</div>
```

Si calculamos la media aritmética de la tasa de crecimiento tenemos: $(0,05 + 0,20 + 0,50)/3 = 0,25$ y el factor medio de expansión sería $1,25$. Sin embargo, si la población hubiera crecido los tres años de esta forma, no se llegaría al mismo resultado final:

```{=html}
<div class="tabla-wrapper2">

<table class="tabla-0202">
  <thead>
    <tr>
      <th style="vertical-align: middle;">Año</th>
      <th>Poblacion <br> inicial</th>
      <th>Tasa de <br> crecimiento</th>
      <th>Factor de <br> expansión</th>
      <th>Población al <br> final del año</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td> <td>10.000</td> <td>0,25</td> <td>1,25</td> <td>12.500</td>
    </tr>
    <tr>
      <td>2</td> <td>12.500</td> <td>0,25</td> <td>1,25</td> <td>15.625</td>
    </tr>
    <tr>
      <td>3</td> <td>15.625</td> <td>0,25</td> <td>1,25</td> <td>19.531</td>
    </tr>
  </tbody>
</table>
</div>
```

Por tanto, la media aritmética no es un buen indicador de la tasa media de crecimiento.

Si la población creciera a una tasa constante $i$, para que al final del tercer año produjera el mismo efecto que las tasas del ejemplo, se debe verificar que:

$$ 10\,000(1+i)(1+i)(1+i)=10\,000(1+0,05)(1+0,20)(1+0,50) $$

De donde:

$$(1+i)= \sqrt[3]{1,05 \cdot 1,20 \cdot 1,50}=1,2364$$

Si se hubiera tenido este factor de expansión cada año (nótese que se trata de la media geométrica), se habría llegado exactamente a la misma población final.

Curiosidades sobre la media geométrica son:

-   A diferencia de la media aritmética, la media geométrica sólo se define para números positivos.

-   La media geométrica nunca es mayor que la media aritmética. La demostración para el caso de dos valores es fácil por reducción al absurdo. Supongamos que: $\sqrt{ab} > (a+b)/2$, entonces $ab > (a^2+2ab+b^2)/4$, de donde se deduce: $0 >a^2-2ab+b^2$. Como $a^2-2ab+b^2=(a-b)^2$ es imposible que este valor sea negativo, luego es imposible que $\sqrt{ab}>(a+b)/2$.

Y ya puestos a hablar de otras medias, podemos hacer un comentario sobre la media armónica\index{media!armónica}, mucho menos conocida pero también útil en algunos casos.

Se define la media armónica de $x_1, x_2, \ldots..., x_N$ como:

$$Mh = \frac{N}{\large{\frac{1}{x_1}+\frac{1}{x_2}+...+\frac{1}{x_N}}}$$

Parece que esto sea un retorcimiento sin ningún interés, pero no. Si un coche recorre cierta distancia a una velocidad de 100 km/h y vuelve por el mismo camino a 120 km/h, la velocidad media del viaje es:

$$Mh = \frac{2}{\large{\frac{1}{100}+\frac{1}{120}}} = 109,1 \text{ km/h}$$

y no 110 km/h como en principio se podría pensar.

Observe que la velocidad es igual a la distancia recorrida dividida por el tiempo tardado en recorrerla,

es decir $v=d/t$ y por tanto $t=d/v$. En nuestro caso, si la distancia a recorrer es $d$, el tiempo tardado en la ida es $t_1 =d/100$ y el tiempo tardado en el regreso es $t_2 =d/120$. De esta manera el tiempo total invertido en todo el recorrido $(2d)$ será $t=t_1+t_2$ y la velocidad media se calcula de la forma:

$$ \text{Velocidad media} = \frac{\text{Distancia total recorrida}}{\text{Tiempo total empleado}} = \frac{2d}{\large{\frac{d}{100}+\frac{d}{120}}} $$

Otro ejemplo: un avión recorre 3000 km. Los 1000 primeros a 700 km/h, los 1000 siguientes a 800 km/h, y los 1000 restantes a 900 km/h ¿Cuál ha sido su velocidad media? No ha sido 800 km/h sino 791,6 km/h.
