# ¿Por qué cuando se calcula la varianza de una muestra se divide por n-1? {.unnumbered #n-1}

Para hacer más fácil la explicación vamos a trabajar con un ejemplo suponiendo que conocemos la población completa, lujo que no tendremos en la práctica. Los elementos que componen la población, junto con sus mediciones respectivas, son:

```{=html}
<h6>
    <table width="350" cellpadding="1"  border="0" class="center" style="margin: 0 auto;">
<tr style="border-bottom:0px solid grey">
<td colspan="100%"></td>
  </tr>
<tr>
<td style="text-align:center">(A)</td>
<td style="text-align:center">(B)</td>
<td style="text-align:center">(C)</td>
<td style="text-align:center">(D)</td>
<td style="text-align:center">(E)</td>
<td style="text-align:center">(F)</td>
</tr>
<tr style="border-bottom:0px solid grey">

<tr>
<td style="text-align:center">2</td>
<td style="text-align:center">6</td>
<td style="text-align:center">8</td>
<td style="text-align:center">10</td>
<td style="text-align:center">10</td>
<td style="text-align:center">12</td>
</tr>
<tr style="border-bottom:0px solid grey">
 </h6> 
 </table>
```
\
En primer lugar ilustraremos la propiedad de insesgamiento de un estimador para el caso de la media, con la cual estamos más familiarizados, y luego repetiremos la experiencia para el caso que nos ocupa de la varianza.

La media poblacional $\mu$, de los datos del ejemplo, es:

$$\mu = \frac{2+6+8+10+10+12}{6}=8$$

Supongamos que nosotros queremos estimar (“hacernos una idea”) el valor $\mu$, usando una muestra aleatoria de $n = 2$ unidades. En este caso, en que la población consta sólo de 6 unidades, podemos hacer un listado de todas las muestras que pueden resultar al escoger dos unidades al azar. Estas muestras aparecen enumeradas en la siguiente tabla:

::: tabla-pequena
<table style="width:98%;">
<colgroup>
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
</colgroup>
<tbody>
<tr class="odd">
<td><p>Muestra nº</p></td>
<td style="text-align: center;"><p>1</p></td>
<td style="text-align: center;"><p>2</p></td>
<td style="text-align: center;"><p>3</p></td>
<td style="text-align: center;"><p>4</p></td>
<td style="text-align: center;"><p>5</p></td>
<td style="text-align: center;"><p>6</p></td>
<td style="text-align: center;"><p>7</p></td>
<td style="text-align: center;"><p>8</p></td>
<td style="text-align: center;"><p>9</p></td>
<td style="text-align: center;"><p>10</p></td>
<td style="text-align: center;"><p>11</p></td>
<td style="text-align: center;"><p>12</p></td>
<td style="text-align: center;"><p>13</p></td>
<td style="text-align: center;"><p>14</p></td>
<td style="text-align: center;"><p>15</p></td>
</tr>
<tr class="even">
<td><p>Unidades de la muestra</p></td>
<td style="text-align: center;"><p>A<br />
B</p></td>
<td style="text-align: center;"><p>A<br />
C</p></td>
<td style="text-align: center;"><p>A<br />
D</p></td>
<td style="text-align: center;"><p>A<br />
E</p></td>
<td style="text-align: center;"><p>A<br />
F</p></td>
<td style="text-align: center;"><p>B<br />
C</p></td>
<td style="text-align: center;"><p>B<br />
D</p></td>
<td style="text-align: center;"><p>B<br />
E</p></td>
<td style="text-align: center;"><p>B<br />
F</p></td>
<td style="text-align: center;"><p>C<br />
D</p></td>
<td style="text-align: center;"><p>C<br />
E</p></td>
<td style="text-align: center;"><p>C<br />
F</p></td>
<td style="text-align: center;"><p>D<br />
E</p></td>
<td style="text-align: center;"><p>D<br />
F</p></td>
<td style="text-align: center;"><p>E<br />
F</p></td>
</tr>
<tr class="odd">
<td><p>Valores en la muestra</p></td>
<td style="text-align: center;"><p>2<br />
6</p></td>
<td style="text-align: center;"><p>2<br />
8</p></td>
<td style="text-align: center;"><p>2<br />
10</p></td>
<td style="text-align: center;"><p>2<br />
10</p></td>
<td style="text-align: center;"><p>2<br />
12</p></td>
<td style="text-align: center;"><p>6<br />
8</p></td>
<td style="text-align: center;"><p>6<br />
10</p></td>
<td style="text-align: center;"><p>6<br />
10</p></td>
<td style="text-align: center;"><p>6<br />
12</p></td>
<td style="text-align: center;"><p>8<br />
10</p></td>
<td style="text-align: center;"><p>8<br />
10</p></td>
<td style="text-align: center;"><p>8<br />
12</p></td>
<td style="text-align: center;"><p>10<br />
10</p></td>
<td style="text-align: center;"><p>10<br />
12</p></td>
<td style="text-align: center;"><p>10<br />
12</p></td>
</tr>
<tr class="even">
<td><p>Media muestral</p></td>
<td style="text-align: center;"><p>4</p></td>
<td style="text-align: center;"><p>5</p></td>
<td style="text-align: center;"><p>6</p></td>
<td style="text-align: center;"><p>6</p></td>
<td style="text-align: center;"><p>7</p></td>
<td style="text-align: center;"><p>7</p></td>
<td style="text-align: center;"><p>8</p></td>
<td style="text-align: center;"><p>8</p></td>
<td style="text-align: center;"><p>9</p></td>
<td style="text-align: center;"><p>9</p></td>
<td style="text-align: center;"><p>9</p></td>
<td style="text-align: center;"><p>10</p></td>
<td style="text-align: center;"><p>10</p></td>
<td style="text-align: center;"><p>11</p></td>
<td style="text-align: center;"><p>11</p></td>
</tr>
</tbody>
</table>
:::

\
Cuando se seleccione al azar una muestra de dos unidades, el resultado será necesariamente alguna de estas 15 posibles combinaciones de 2 elementos, con su media $\bar{x}$ correspondiente.

Decimos que $\bar{x}$ es un estimador insesgado de $\mu$ si el promedio de todas las posibles medias coincide exactamente con la media de la población. Para verificarlo, hagamos el promedio de nuestras 15 posibles medias: $$ \frac{4+5+6+6+7+7+8+8+9+9+9+10+10+11+11}{15}=8 $$

El promedio coincide con $\mu$. Esto pasa en todos los casos, independientemente del tipo de población o del tamaño de la muestra, por eso decimos que $\bar{x}$ es un estimador insesgado de $\mu$.

Veamos ahora si el estadístico: $$  S_{n}^{2}= \frac{ \sum_{i=1}^{n}{(x_i-\bar{x})^2} }{n} $$

donde $n$ es el tamaño de las muestras, es un estimador insesgado para la varianza $\sigma_{N}^{2}$, calculada como: $$  \sigma_{N}^{2}= \frac{ \sum_{i=1}^{N}{(x_i-\mu)^2} }{N} $$

donde $N$ es el tamaño de la población. Queremos saber si el promedio de los valores de $S_{n}^{2}$, para cada una de las posibles muestras, da el valor de $\sigma_{N}^{2}$ y para averiguarlo, en primer lugar vamos a calcular la varianza poblacional:

$$  \sigma_{N}^{2}= \frac{(2-8)^2+(6-8)^2+(8-8)^2+...+(12-8)^2}{6} = 10,67 $$

Ahora calculamos la varianza para cada muestra de 2 unidades, con la fórmula: $$  S_{n}^{2}= \frac{ (x_1 - \bar{x})^2 + (x_2 - \bar{x})^2 }{2} $$

obteniéndose los resultados que aparecen en la siguiente tabla:

::: tabla-pequena
<table style="width:98%;">
<colgroup>
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
<col style="width: 6%" />
</colgroup>
<tbody>
<tr class="odd">
<td><p>Muestra nº</p></td>
<td style="text-align: center;"><p>1</p></td>
<td style="text-align: center;"><p>2</p></td>
<td style="text-align: center;"><p>3</p></td>
<td style="text-align: center;"><p>4</p></td>
<td style="text-align: center;"><p>5</p></td>
<td style="text-align: center;"><p>6</p></td>
<td style="text-align: center;"><p>7</p></td>
<td style="text-align: center;"><p>8</p></td>
<td style="text-align: center;"><p>9</p></td>
<td style="text-align: center;"><p>10</p></td>
<td style="text-align: center;"><p>11</p></td>
<td style="text-align: center;"><p>12</p></td>
<td style="text-align: center;"><p>13</p></td>
<td style="text-align: center;"><p>14</p></td>
<td style="text-align: center;"><p>15</p></td>
</tr>
<tr class="even">
<td><p>Valores en la muestra</p></td>
<td style="text-align: center;"><p>2<br />
6</p></td>
<td style="text-align: center;"><p>2<br />
8</p></td>
<td style="text-align: center;"><p>2<br />
10</p></td>
<td style="text-align: center;"><p>2<br />
10</p></td>
<td style="text-align: center;"><p>2<br />
12</p></td>
<td style="text-align: center;"><p>6<br />
8</p></td>
<td style="text-align: center;"><p>6<br />
10</p></td>
<td style="text-align: center;"><p>6<br />
10</p></td>
<td style="text-align: center;"><p>6<br />
12</p></td>
<td style="text-align: center;"><p>8<br />
10</p></td>
<td style="text-align: center;"><p>8<br />
10</p></td>
<td style="text-align: center;"><p>8<br />
12</p></td>
<td style="text-align: center;"><p>10<br />
10</p></td>
<td style="text-align: center;"><p>10<br />
12</p></td>
<td style="text-align: center;"><p>10<br />
12</p></td>
</tr>
<tr class="odd">
<td><p>Media muestral</p></td>
<td style="text-align: center;"><p>4</p></td>
<td style="text-align: center;"><p>9</p></td>
<td style="text-align: center;"><p>16</p></td>
<td style="text-align: center;"><p>16</p></td>
<td style="text-align: center;"><p>25</p></td>
<td style="text-align: center;"><p>1</p></td>
<td style="text-align: center;"><p>4</p></td>
<td style="text-align: center;"><p>4</p></td>
<td style="text-align: center;"><p>9</p></td>
<td style="text-align: center;"><p>1</p></td>
<td style="text-align: center;"><p>1</p></td>
<td style="text-align: center;"><p>4</p></td>
<td style="text-align: center;"><p>0</p></td>
<td style="text-align: center;"><p>1</p></td>
<td style="text-align: center;"><p>1</p></td>
</tr>
</tbody>
</table>
:::

\

Veamos si el promedio de las posibles varianzas muestrales, coincide con 10,67 que es el valor obtenido para $\sigma_{N}^{2}$.

$$ \bar{S}^2 = \frac{4+9+16+16+25+1+4+4+9+...+1}{15} = 6,4 $$

No coincide y, por tanto, $S_{n}^{2}$ no es un estimador insesgado de $\sigma_{N}^{2}$. Sin embargo $S_{n-1}^{2}$, definido de la forma: $$  S_{n-1}^{2}= \frac{ \sum_{i=1}^{n}{(x_i-\bar{x})^2} }{n-1} $$

aunque tampoco es un estimador insesgado para $\sigma_{N}^{2}$, sí lo es para $\sigma_{N-1}^{2}$ definido como: $$  \sigma_{N-1}^{2}= \frac{ \sum_{i=1}^{N-1}{(x_i-\mu)^2} }{N-1} $$

Efectivamente, $\sigma_{N-1}^{2$ tiene el valor: $$  \sigma_{N-1}^{2}= \frac{(2-8)^2+(6-8)^2+(8-8)^2+...+(12-8)^2}{6-1} = 12,8 $$

Y si calculamos $S_{n-1}^{2}$ para cada una de nuestras muestras deberemos aplicar la fórmula:

$$  S_{n-1}^{2}= \frac{ (x_1 - \bar{x})^2 + (x_2 - \bar{x})^2 }{2-1} = \frac{ (x_1 - \bar{x})^2 + (x_2 - \bar{x})^2 }{1}  $$

Es decir que todos los valores de la varianza que aparecen en la tabla anterior, quedan ahora multiplicados por 2 y por lo tanto la media de las varianzas queda también multiplicada por 2, es decir:

$$ \bar{S}_{n-1}^{2}= 2\cdot 6,4 = 12,8 $$

Quizá este resultado decepcione, y hasta sorprenda, porque seguramente lo esperado era que $S_{n-1}^{2}$ fuera un estimador insesgado de $\sigma_{N}^{2}$ y no de $\sigma_{N-1}^{2}$, pero no hay que preocuparse demasiado. A efectos prácticos es casi lo mismo cuando la población es grande, y nosotros no vamos a estimar a través de muestras las características de una población de 6 elementos (en nuestro ejemplo esta ha sido una población “de juguete” para entender lo que estábamos haciendo). Cuando estimemos la varianza de una población se tratará de una población grande, en la que $\sigma_{N}^{2}$ será prácticamente igual a $\sigma_{N-1}^{2}$. En realidad, el caso más frecuente es tener poblaciones teóricas (infinitas), en las que es exactamente lo mismo $\sigma_{N}^{2}$ que $\sigma_{N-1}^{2}$.
