# 2.6 ¿Por qué la desviación típica es la medida típica de dispersión? {#tipica .unnumbered}

Existen diversas razones por las que la desviación típica --o desviación estándar-- es tan valorada y tan necesaria en el ámbito de la estadística. Una de esas razones es que, junto con la media, forman una "pareja perfecta" para describir el comportamiento de muchas variables aleatorias. Otra podría ser el formar parte del "ADN" de la distribución Normal. Veamos algunos de sus méritos.

#### Relación con la media y con la distribución Normal}

Si una variable aleatoria tiene distribución Normal, basta conocer su media y su desviación típica para calcular cualquier probabilidad relacionada con los valores que puede tomar. Si el peso de unos paquetes de azúcar sigue una distribución Normal con una media de 1000 g y una desviación típica de 15 g, podemos decir que aproximadamente el 95 % de los paquetes tendrán un peso comprendido entre 970 y 1030 g, y también podemos decir que el 68 % tendrá un peso comprendido entre 985 y 1015 g. Además, podríamos responder cualquier pregunta similar, por ejemplo qué porcentaje de paquetes tendrá un peso por debajo de 980 g (será el 9 %).

#### Importancia en otras distribuciones

Si la variable considerada no sigue una distribución Normal ¿sigue siendo útil la desviación típica? La respuesta es sorprendente. Si la variable sigue un modelo de probabilidad exponencial, o de Poisson, o una distribución Gamma, o una Beta, entre otras, también podemos usar la media y la desviación típica para responder preguntas de naturaleza similar a las planteadas antes.

#### Cuando no se conoce la distribución

\noindent ¿Sirve la desviación típica para hacer cálculos aproximados de probabilidades asociadas a una variable aleatoria si no tenemos ni idea de cuál es su distribución? Esta pregunta la respondió el matemático ruso Pafnuty Chebyshev (su apellido se puede ver escrito de distintas formas) \index{desigualdad de Chebyshev} en la conocida como desigualdad de Chebyshev. La idea es que para una amplia variedad de distribuciones, en el intervalo $\mu \pm k\sigma$ se tiene como mínimo una proporción de observaciones igual a $1-1/k^2$. Es decir, si $k=\sqrt{2}$, el intervalo es $\mu \pm \sqrt{2}\sigma$ y podemos afirmar que, con independencia del tipo de distribución, tendremos como mínimo el 50 % de las observaciones dentro de ese intervalo, y si $k=2$ tendremos como mínimo el 75 %. Una curiosa propiedad en la que nuestra pareja media--desviación típica también es protagonista.

#### Su papel en la estimación de la media poblacional

En muchas situaciones nuestro interés está en estimar la media poblacional $\mu$. Para ello tomamos una muestra y calculamos su media $\bar{x}$ para hacernos una idea del valor desconocido del parámetro $\mu$.

Cada vez que se tome una muestra, el valor de la media muestral $\bar{x}$ cambiará, pero sabemos que si tomamos muchas muestras de tamaño $n$, sus medias estarán alrededor del verdadero valor de la media poblacional $\mu$. Pero decir que están alrededor de $\mu$ no significa que estén cerca de $\mu$. ¿Cómo podemos saber qué tan cerca están? En la respuesta a esta pregunta la desviación típica también tiene un papel protagonista. La desviación típica de esas medias muestrales se llama error típico y \textbf{siempre} es igual a la desviación típica de la población dividida por $\sqrt{n}$. Esto es verdad para \textbf{todas} las distribuciones, no solo para la Normal.

#### Estandarización de los datos

Si le dicen que una vaca pesa 600 kg, a no ser que usted sea ganadero, probablemente ese valor no le dirá si la vaca está muy delgada o si tiene el peso correcto. Sin embargo, si le dicen que su peso está a 0,6 desviaciones típicas por encima de la media podrá deducir que el 73 % de las vacas de ese tipo tienen un peso por debajo y un 27 % por encima, luego la vaca no está delgada.

Usando un ejemplo más académico, lo mismo ocurre con los residuos que se obtienen después de ajustar una ecuación de regresión. Que un residuo sea igual a 10 no nos dice si es grande o pequeño, es mucho más informativo que nos digan a cuantas desviaciones típicas está de la media, que en este caso siempre es cero. A ese valor se le llama residuo estandarizado.

En definitiva, la desviación típica aparece en muchos contextos y con mucha relevancia. El calificativo "típica" resulta en este caso apropiado y bien merecido.
