# 4.4 ¿Cuántos elementos debe tener una muestra para que las conclusiones sean fiables? {#elementosMuestra .unnumbered}

En el ámbito del muestreo probabilístico, el tamaño de la muestra se calcula aplicando una fórmula que puede ser más o menos complicada, dependiendo del tipo de muestreo. En el caso del muestreo aleatorio simple y para la estimación de una proporción, $p$, tenemos: $$ n = \frac{Np(1-p)}{(N-1)(E^2/z^2)+p(1-p)} $$

\noindent Esta fórmula se deduce a partir de la expresión del intervalo de confianza para $p$ con la corrección para población finita. Para obtener el valor de $n$ basta con asignar valores a las variables que intervienen. Estas variables son:

##### ***E***: Margen de error

Si le piden que a través de una muestra estime la proporción de jóvenes de su ciudad que son usuarios habituales de una red social, nadie le va a exigir que dé el valor exacto, por ejemplo el 23,7 %. En su informe usted hará constar que el porcentaje estimado es de 23,7 $\pm$ 3,3 %. El 23,7 % es la proporción obtenida en la muestra y ese 3,3 % de incertidumbre en torno al valor de la muestra es lo que llamamos margen de error. En igualdad de valores del resto de variables que intervienen, si quiere dar el resultado con menos margen de error deberá usar un mayor tamaño de muestra.

##### ***z***: Relacionado con el nivel de confianza

Si llega a la conclusión de que esa proporción está en el intervalo 23,7 $\pm$ 3,3 % ¿Puede usted afirmar con total seguridad que el verdadero valor está dentro de este intervalo? No, no puede hacerlo, su afirmación siempre tendrá un cierto nivel de confianza. Si ese nivel de confianza es del 95 % significa que el intervalo se ha construido siguiendo un procedimiento que acierta (incluye el verdadero valor) el 95 % de las veces, es como una información que da alguien que dice la verdad el 95 % de las veces. El nivel de confianza está relacionado con el valor de $z$. Para un nivel de confianza $1-\alpha$ el valor de $z$ es aquel que deja un área de cola de $\alpha/2$ en la distribución $N(0; 1)$. Si el nivel de confianza es el 95 % tenemos que $z_{0,025} = 1,96$ (cuando los medios de cálculo eran rudimentarios ese 1,96 se redondeaba a 2 obteniéndose un nivel de confianza del 95,5 %). ¿Podemos construir el intervalo de manera que acierte el 99 % de las veces? Sí podemos, incluso podemos lograr que acierte el 99,99 %, pero no lo hacemos porque al aumentar el nivel de confianza aumenta también el margen de error y podemos llegar a la conclusión de que el porcentaje que andamos buscando está en el intervalo 23,7 $\pm$ 20 %. De eso estaremos muy seguros pero no hacía falta ningún estudio para llegar a esa conclusión.

En general, la determinación del margen de error y del nivel de confianza "adecuados", no es un tema de la Estadística, ni de los estadísticos, es una decisión del equipo de investigación, que tiene conocimiento de los riesgos reales de equivocarse y del presupuesto disponible.

##### ***p***: La variabilidad en la población

Si en una población no hay variabilidad basta con mirar un solo elemento para saber cómo son todos. Cuando la variabilidad aumenta también lo hace el tamaño de muestra necesario para estimar sus características. Si se trata de estimar una proporción esa variabilidad está relacionada con el valor de la propia proporción $p$, o más concretamente con $p(1-p)$. Aquí aparece un problema porque si queremos estimar una proporción no podemos usar el valor de esa proporción --que no conocemos-- para calcular el tamaño de muestra necesario. La solución es calcular el tamaño de la muestra poniéndonos en el caso más desfavorable que es cuando $p = 50\%$. A $1-p$ también se le denomina $q$, por esta razón muchas veces se habla del supuesto de $p=q=50 %$ en las fichas técnicas de las encuestas.

##### ***N***: El tamaño de la población

Parece que esta es la variable cuya influencia está más justificada, pero no es así. Si la población es grande --y esto es lo más habitual-- su tamaño prácticamente no influye. Usando la fórmula que hemos visto y con la ayuda de una hoja de cálculo se puede construir la siguiente tabla donde se aprecia la poca influencia del tamaño de la población.

```{=html}
<style>
/* Selecciona cada 5ª fila del cuerpo de la tabla */
table tbody tr:nth-child(5n) {
    border-bottom: 1px solid #d3d3d3 !important;
}
</style>
<div class="tabla-wrapper0404">
 <table class="tabla-0404">

<colgroup>
<col style="width: 28%" />
<col style="width: 12%" />
<col style="width: 12%" />
<col style="width: 12%" />
<col style="width: 12%" />
<col style="width: 12%" />
<col style="width: 12%" />
</colgroup>

<caption style="caption-side:top; text-align:center; font-size:1em; font-style:italic; margin-bottom:0.5em;"> 
Tamaños de muestra para la estimación de una proporción con un nivel de confianza del 95 %
</caption>

  <thead>
    <tr style="border-top:1px solid #000; border-bottom:1px solid #000;">
      <th rowspan="2" style="padding:4px;">Tamaño de <br>la población</th>
      <th colspan="6" style="padding:4px;">Margen de error</th>
    </tr>
    <tr style="border-bottom:1px solid #000;">
      <th>±1 %</th> <th>±2 %</th> <th>±3 %</th> <th>±4 %</th> <th>±5 %</th> <th>±10 %</th>
    </tr>
  </thead>

  <tbody>
    <tr><td>500</td><td>476</td><td>414</td><td>341</td><td>273</td><td>218</td><td>81</td></tr>
    <tr><td>1.000</td><td>906</td><td>707</td><td>517</td><td>376</td><td>278</td><td>88</td></tr>
    <tr><td>1.500</td><td>1.298</td><td>924</td><td>624</td><td>429</td><td>306</td><td>91</td></tr>
    <tr><td>2.000</td><td>1.656</td><td>1.092</td><td>697</td><td>462</td><td>323</td><td>92</td></tr>
    <tr><td>2.500</td><td>1.984</td><td>1.225</td><td>749</td><td>485</td><td>334</td><td>93</td></tr>
    <tr><td>3.000</td><td>2.287</td><td>1.334</td><td>788</td><td>501</td><td>341</td><td>94</td></tr>
    <tr><td>3.500</td><td>2.566</td><td>1.425</td><td>818</td><td>513</td><td>347</td><td>94</td></tr>
    <tr><td>4.000</td><td>2.825</td><td>1.501</td><td>843</td><td>523</td><td>351</td><td>94</td></tr>
    <tr><td>4.500</td><td>3.065</td><td>1.566</td><td>863</td><td>530</td><td>355</td><td>95</td></tr>
    <tr><td>5.000</td><td>3.289</td><td>1.623</td><td>880</td><td>536</td><td>357</td><td>95</td></tr>
    <tr><td>6.000</td><td>3.694</td><td>1.715</td><td>907</td><td>546</td><td>362</td><td>95</td></tr>
    <tr><td>7.000</td><td>4.050</td><td>1.788</td><td>927</td><td>553</td><td>365</td><td>95</td></tr>
    <tr><td>8.000</td><td>4.365</td><td>1.847</td><td>942</td><td>559</td><td>367</td><td>95</td></tr>
    <tr><td>9.000</td><td>4.647</td><td>1.896</td><td>955</td><td>563</td><td>369</td><td>96</td></tr>
    <tr><td>10.000</td><td>4.900</td><td>1.937</td><td>965</td><td>567</td><td>370</td><td>96</td></tr>
    <tr><td>15.000</td><td>5.856</td><td>2.070</td><td>997</td><td>578</td><td>375</td><td>96</td></tr>
    <tr><td>20.000</td><td>6.489</td><td>2.144</td><td>1.014</td><td>583</td><td>377</td><td>96</td></tr>
    <tr><td>25.000</td><td>6.939</td><td>2.191</td><td>1.024</td><td>587</td><td>379</td><td>96</td></tr>
    <tr><td>50.000</td><td>8.057</td><td>2.291</td><td>1.045</td><td>594</td><td>382</td><td>96</td></tr>
    <tr><td>100.000</td><td>8.763</td><td>2.345</td><td>1.056</td><td>597</td><td>383</td><td>96</td></tr>
    <tr><td>500.000</td><td>9.423</td><td>2.390</td><td>1.065</td><td>600</td><td>384</td><td>97</td></tr>
    <tr><td>1.000.000</td><td>9.513</td><td>2.396</td><td>1.066</td><td>600</td><td>384</td><td>97</td></tr>
    <tr><td>1.500.000</td><td>9.543</td><td>2.398</td><td>1.067</td><td>600</td><td>385</td><td>97</td></tr>
    <tr><td>2.000.000</td><td>9.558</td><td>2.399</td><td>1.067</td><td>601</td><td>385</td><td>97</td></tr>
    <tr>
      <td>50.000.000</td><td>9.602</td><td>2.401</td><td>1.068</td><td>601</td><td>385</td><td>97</td>
    </tr>
  </tbody>
</table>
</div>
```

Aunque no aparece en la fórmula, el presupuesto disponible (tiempo, dinero, recursos) es seguramente la variable más influyente, de manera que muy a menudo la muestra es tan grande como los recursos permiten. En este caso, dado el tamaño de muestra, y establecido un nivel de confianza, se puede calcular el margen de error obtenido.
