# ¿Qué tipo de muestreo conviene elegir? {.unnumbered #tipoMuestreo}

Los tipos de muestreo se pueden dividir en dos grandes grupos: muestreo *probabilístico* y muestreo *no probabilístico*.

#### Muestreo probabilístico

El más típico --en los libros-- es el muestreo probabilístico. La idea es tomar una muestra al azar (siempre más fácil de decir que de hacer) y en función de la estrategia seguida y de los resultados obtenidos se construyen los intervalos de confianza y se dan márgenes de error usando razonamientos puramente matemáticos. Según la estrategia seguida para seleccionar la muestra el muestreo probabilístico puede ser (la lista no es exhaustiva):

-   **Aleatorio simple**: Se elige la muestra al azar de entre todo el conjunto de la población. Seguramente el más fácil de tratar en la teoría y el más difícil de llevar a cabo en la práctica.

-   **Estratificado**: Se divide la población en estratos homogéneos y se extrae una muestra de cada estrato. Dado un mismo tamaño de muestra global permite realizar estimaciones más precisas para cada estrato.

-   **Sistemático**: Se selecciona la muestra siguiendo un criterio que facilita la selección y evita discrecionalidad, que en general no es lo mismo que aleatoriedad. Por ejemplo, en las entrevistas a pie de urna se va preguntando a uno de cada 10 por orden de salida.

-   **Multietápico**: Primero se seleccionan zonas (barrios, estanterías del almacén,...) y dentro de cada zona se seccionan unidades (individuos, piezas,...). En general es menos costoso porque las unidades están agrupadas y cuesta menos llegar a ellas.

#### Muestreo no probabilístico

El problema del muestreo probabilístico es que en muchos casos la selección al azar no es viable, especialmente en el ámbito de las ciencias sociales. En estos casos no hay más remedio que usar métodos de muestreo no probabilístico, entre estos se encuentran:

-   **Muestreo por cuotas**: Se trata de definir grupos que tengan la máxima homogeneidad. La selección dentro de cada grupo no se realiza al azar sino que cualquier persona que cumpla los requisitos del grupo puede ser incluida en la muestra (al haber poca variabilidad dentro de cada grupo cualquier individuo puede ser un buen representante). Este procedimiento se adapta muy bien a las entrevistas telefónicas marcando números al azar. La entrevista se puede realizar a la persona que responde si no está completo el grupo al que pertenece, o se puede preguntar si en el hogar hay alguien con el perfil de un grupo que todavía esté sin completar. Cuando todos los grupos se han completado se entiende que la muestra es un buen reflejo de la población.

-   **Muestreo razonado**: En ocasiones lo más conveniente puede ser tomar una muestra que responda a unas características específicas. Por ejemplo, si se viene comprobando que los resultados en un colegio electoral son un buen reflejo de lo que ocurre en todo el país, tomar a los votantes de ese colegio como muestra de todo el país puede ser lo más adecuado.

-   **Encuestas informales**: Programa de televisión: "Salimos a la calle y preguntamos la opinión de los ciudadanos sobre...". Más allá del tamaño de la muestra, los que pasan por ese sitio a esa hora y se prestan a responder delante de la cámara, no son una muestra representativa de la población. Casi siempre es evidente que se trata de un. Lo peor es cuando en un trabajo académico se realiza una encuesta más o menos de este tipo y se pretende dar a los resultados un valor que no tienen (a veces incluyendo niveles de confianza y márgenes de error).

-   **Encuestas de cortesía**: En algunas ocasiones se nos pide que rellenemos un cuestionario dando nuestra opinión sobre un producto o servicio. En general solo responden los que están muy descontentos o muy satisfechos. La encuesta puede servir para detectar esos casos, pero es evidente que sus resultados no se pueden extrapolar a todos los clientes.

#### ¿Qué tipo elegir?

En contextos relacionados con la ingeniería, donde la población es un conjunto de unidades físicas (lote de producción, existencias en el almacén…) el muestreo probabilístico es, en general, una buena opción porque es relativamente fácil (o al menos es viable) elegir la muestra aleatoriamente

En el ámbito de las ciencias sociales es mucho más difícil disponer de muestras verdaderamente aleatorias por lo que en muchos casos no queda más remedio que optar por muestreos no probabilísticos. Dentro de este grupo también está el *hacer lo que se pueda* sacando el máximo provecho a los recursos disponibles.

Lo que no debe hacerse es utilizar muestras claramente no aleatorias y presentar los resultados ignorando ese *detalle*. Presentar niveles de confianza y márgenes de error puede dar un aire científico al estudio, pero si las muestras no son aleatorias esos valores son totalmente arbitrarios. Es como si le dicen \`Supongamos que una castaña es una esfera...'' y partir de ahí llegan a una serie de conclusiones sobre el comportamiento y las características geométricas de las castañas. No hay ninguna garantía de que esas conclusiones sean ciertas, no porque el método usado para obtenerlas sea incorrecto --puede ser una deducción impecable--, sino porque la hipótesis en que se basa es falsa. Exactamente lo mismo ocurre cuando se dice "Bajo la hipótesis de muestreo aleatorio simple..." y a continuación se dan márgenes de error, niveles de confianza y demás jerga estadística. En la presentación de trabajos académicos esto puede servir para dar un aire de rigor científico y enfriar las ganas de preguntar que pueden tener los miembros del jurado poco duchos en estas cosas, pero solo para eso.

Para conocer la opinión de una población de interés, existen otros métodos además de las encuestas. En estudios de mercado suelen utilizarse los llamados *focus groups*. Se trata de elegir un grupo reducido de personas --en torno a 8 o 10-- que incluya representantes de distintos sectores de la población de interés. Las conversaciones/entrevistas con estas personas, llevadas a cabo por personal experto, permiten obtener información para valorar en nivel de satisfacción con un producto o servicio y también obtener ideas para mejorarlo.
