# ¿Es lo mismo muestra aleatoria que muestra representativa? {.unnumbered}

 No, no es lo mismo. Ni por ser aleatoria ya es representativa, ni que sea representativa implica que sea aleatoria.

Para que una muestra aleatoria sea representativa es necesario que esta tenga un cierto tamaño. Si en la población existen 7 estratos sociales y se toma una muestra de 5 individuos, por muy aleatoria que sea esa muestra no será representativa de la población.

Sí se pueden tener muestras representativas sin ningún tipo de selección aleatoria. Esto es lo que se pretende con el muestreo por cuotas. Naturalmente, hay que tener muy clara la estructura de la población, saber dividirla en grupos homogéneos y asignar a cada grupo el peso o el tamaño que le corresponde. Si todo se hace correctamente, esa muestra puede considerarse representativa, aunque el entrevistador se haga una autoentrevista, y se la haga también a sus padres y a su novia, siempre que pertenezcan a grupos especificados en el plan de muestreo.

Ya que estamos en este tema, tres reflexiones sobre la representatividad:

-   El término "representante", o "representativo", muchas veces se utiliza con un sentido distinto al que damos en estadística. Así, por ejemplo, cuando se pregunta por un escritor representativo de Colombia en muchas ocasiones se responde que Gabriel García Márquez, aunque seguramente este es el más atípico de los escritores colombianos. O cuando se habla de los atletas representantes de un país en una olimpiadas, seguro que no son representativos -al menos en forma física- de los ciudadanos de ese país.

-   Tenemos una tendencia innata a considerar representativa y, por tanto, a generalizar, en base a muestras muy pequeñas. A veces en base a muestras de una sola observación: ``Este remedio va muy bien, a mi vecino le funcionó''.

-   Las muestras autoseleccionadas nunca son representativas. Es una práctica habitual hacer encuestas enviando cuestionarios y sacando conclusiones a partir de los que responden, como si esos fueran una muestra representativa. Los que responden son los que están interesados en el tema de la encuesta, si se pregunta sobre cuanto se recicla responderán más los que están más sensibilizados con los problemas del medio ambiente y, por tanto, los que más reciclan. 

Si usted quiere estimar las características de una población de 1000 empresas y envía un cuestionario a todas ellas, con mucha suerte le responderán 200. Quizá este le parezca un buen número y piense que a partir de ahí se pueden sacar unas buenas conclusiones, pero será mucho más representativa una muestra de 50 empresas elegidas al azar y perseguidas hasta tener su opinión que la de 200 autoseleccionadas. Claro que el margen de error le saldrá mayor con 50 empresas que con 200, pero el primero será cierto y útil y el otro ni una cosa ni otra.

#### ¿Como saber si mi muestra es representativa?

No existen test de representatividad, y es una lástima porque en muchos estudios estadísticos, donde hay profusión de test de todo tipo, se pasa por alto la justificación de la representatividad de la muestra como si esa fuera una característica innata de todas las muestras y no fuera necesario justificarla.

Una forma de verificar la representatividad es comprobar que se resiste un duro interrogatorio que lo ponga en duda. Imagínese que le cuestionan esa representatividad por todas las razones que pueda imaginar (por ejemplo, usted solo ha entrevistado a los que vio con actitud de querer colaborar, y esos tendían a tener un determinada opinión...). Solo si es capaz de rebatir de manera convincente todas y cada uno de esas objeciones podrá considerar que su muestra es representativa.

