# ¿Por qué cuesta acertar en los sondeos electorales? {.unnumbered}

Cuando se estiman las características de una población a partir de una muestra siempre hay que asumir un cierto margen de error, pero cuando ese error va más allá de lo esperado es que falla algo. No es que no se cumpla la teoría estadística, lo que es que no se cumple son los principios en que se basa, ya sea por falta de recursos o porque en la práctica es muy difícil cumplirlos. Veamos algunas de estas dificultades.

#### Conseguir que la muestra sea representativa

Este no es un problema específico de los sondeos electorales pero es más difícil conseguir la muestra adecuada si una parte de la población se muestra renuente a responder preguntas sobre sus ideas políticas. Si las razones de no respuesta fueran independientes de las preferencias de voto, el problema tendría solución desde la estadística. Sin embargo, la práctica ha demostrado que esto no es así, hay más voto oculto en unas opciones políticas que en otras, y el problema se complica.

#### La intención de voto va cambiando

Los sondeos electorales se basan en encuestas realizadas varios días, o incluso varias semanas, antes de las elecciones. En algunos países está prohibido publicar resultados de sondeos electorales durante un cierto periodo de tiempo antes de las elecciones. Por tanto, nos encontramos con dos tipos de extrapolaciones: 1) La que se hace desde la muestra hacia la población, siendo esta la que trata la teoría estadística del muestreo, y 2) La que generaliza los resultados de las fechas en que se ha hecho el sondeo, al día de las elecciones. Pero los partidos se emplean a fondo en sus campañas electorales, se producen debates entre candidatos, pueden ocurrir sucesos sobre los que se posicionan los candidatos, y todo esto puede afectar a la decisión final de a quien se vota.

#### ¿A quién votarán los indecisos?

Los indecisos suelen representar un porcentaje importante de la población y depende de lo que estos acaben votando los resultados serán unos u otros. Realizar las estimaciones ignorando a los indecisos no es una buena idea porque estos acabarán votando (al menos una gran parte). Suponer que entre los indecisos se reproducirán las mismas proporciones que entre los que ya han decidido su voto también es mucho suponer.

Las empresas especializadas en realizar sondeos electorales tienen sus procedimientos para asignar el voto a los indecisos. Las entrevistas empiezan con preguntas ``fáciles'' (edad, profesión,...) que permiten asignar un cierto perfil socioeconómico a los entrevistados. A continuación se pueden hacer preguntas más relacionadas con la ideología, como su opinión sobre un tema polémico en el que derecha e izquierda tienen opiniones contrapuestas, su valoración de algunos líderes políticos o a quien votó en las últimas elecciones. La respuesta a estas preguntas marca un perfil al que se asigna un voto. La correcta asignación de este voto responde más a conocimientos relacionados con la sociología y con la política que con la estadística, y en esa correcta asignación está el éxito o el fracaso de los resultados del sondeo. 

#### La falta de sinceridad en las respuestas

La redacción de las preguntas y el orden en que se realizan son aspectos críticos para conseguir la participación y la sinceridad de los encuestados. Por otra parte, conseguir que el entrevistado se sienta cómodo y responda con sinceridad requiere entrevistadores bien entrenados y motivados (léase bien pagados). 

A veces la situación política hace que algunos ciudadanos prefieran disimular sus preferencias declarando que votaran a las opciones que consideran ``mejor vistas''. También puede ocurrir que se muestren indecisos cuando en realidad se trata de  “decisos cautos”.

#### Del porcentaje de votos al número de escaños

En muchas ocasiones lo verdaderamente relevante no es el porcentaje de votos sino el número de escaños que va a obtener cada partido. Pequeñas variaciones en el porcentaje de votos --imposibles de precisar-- provocan cambios en el número de escaños.

Otro problema es que algunas legislaciones electorales exigen un mínimo porcentaje de votos para entrar en el reparto. Si ese porcentaje es del 5 % y la estimación de voto para un partido es del 4$\pm$2 % no se puede saber si llegará o no al mínimo necesario, y el hecho de que llegue o no llegue afectará también al número de escaños del resto de partidos.


$$ \bullet \;\;\;\;\; \bullet \;\;\;\;\; \bullet $$

A pesar de las dificultades comentadas, las empresas especializadas saben como hacer las estimaciones en base a su experiencia aplicando técnicas y conocimientos que van más allá de los procedimientos clásicos de estimación estadística. Sus resultados siempre son esperados con interés y muchas veces el grado de acercamiento a lo que al final acaba ocurriendo es espectacular. Claro que, como en otros ámbitos, siempre se destacan más los fallos que los aciertos.

