# ¿A partir de qué p-valor se debe rechazar la hipótesis nula? {.unnumbered}

A todos nos gustan las reglas claras y sencillas, pero no es sensato tomar un p-valor como frontera universal y aplicarlo siempre con independencia del contexto en que esté situado. Fijar un valor frontera es lo mismo que decidir la probabilidad de equivocarnos si se rechaza la hipótesis nula, y la probabilidad de error que es razonable asumir depende de la situación en la que estemos y de las consecuencias de cometer ese error.

Supongamos que un día por la mañana al salir de casa miramos como está el tiempo y consideramos que hay una probabilidad del 10 % de que llueva ¿debemos volvernos a coger el paraguas? A nadie le parecerá temerario que sigamos y corramos un riesgo del 10 % de que la lluvia nos pille desprotegidos. Si nos equivocamos no perdemos mucho (quizá nos mojemos un poco) y también hay que considerar que ir todo el día con el paraguas sin llover es bastante incómodo.

Otra situación. Vamos conduciendo por una carretera secundaria muy poco transitada. En un cambio de rasante, sin ninguna visibilidad de los coches que vienen de frente, vemos que hay un pequeño bache en el lugar por donde debemos pasar, aunque lo podríamos evitar colocándonos a la izquierda. Pero no lo haremos. La probabilidad de que por esa carretera tan poco transitada nos crucemos con un coche es pequeña, y que nos crucemos justo en el cambio de rasante es mucho menor. Pero no lo haremos porque aunque la probabilidad es muy pequeña, si se produce nos perjudica mucho (muchísimo). Es evidente que la probabilidad de error que estamos dispuestos a correr al tomar una decisión depende de las circunstancias y de lo que nos costaría ese error.

Por tanto, la respuesta a la pregunta planteada no es de carácter estadístico, sino que está relacionada con el contexto del problema que se está tratando. Cuando se realiza una prueba para analizar si un nuevo fármaco es mejor que el actual, tomar como valor frontera 0,05 significa que corremos un riesgo del 5 % de decir que es mejor cuando en realidad no lo es. ¿Qué implicaciones tiene esto? ¿Puede tener el nuevo tratamiento efectos secundarios perjudiciales? ¿Es mucho más caro que el tratamiento convencional? La respuesta a los interrogantes planteados son importantes para fijar el valor frontera más conveniente.

Pero también es verdad que en muchos casos se toma como referencia el valor de 0,05 sin entrar en más consideraciones. El porqué se utiliza 0,05 tiene que ver con los valores que figuran en las tablas. Cuando se empezaron a elaborar, con unos medios muy rudimentarios, sólo se tabularon los valores correspondientes a algunas probabilidades –números fáciles como 0,001, 0,005; 0,01; 0,05, 0,10,…– y de entre los disponibles, se acostumbró a tomar el correspondiente a 0,05 como el más adecuado para separar lo habitual de lo raro. La ventaja del 0,05 es ser un valor redondo en nuestro sistema decimal. Si tuviéramos 6 dedos seguramente consideraríamos más natural tomar decisiones utilizando el 0,06 como valor frontera.
