# 6.9 ¿Qué hacer si al aleatorizar aparece el orden estándar de la matriz de diseño? {.unnumbered #aleatorizar}

Siempre se insiste en que una cosa es el orden en que se presenta la matriz de diseño (relación de las condiciones en que se va a experimentar) y otra el orden en que se deben realizar los experimentos. La matriz de diseño se presenta en el llamado “orden estándar” tanto por sus ventajas a la hora de escribirla (la regla de construcción es muy fácil) como por la comodidad de tener un orden establecido al que nos podemos referir sin tener que detallar cuáles son las condiciones una a una.

```{=html}
<div class="tabla-wrapper0609">
<table class="tabla-0609">

<caption style="caption-side:top; text-align:center; font-size:1em; font-style:italic; margin-bottom:0.5em;"> 
Matriz de un diseño 2<sup>3</sup> en orden estándar.
</caption>

  <thead>
    <tr>
        <th rowspan="2"> Orden </th>
        <th colspan="3">Matriz de diseño</th>
        <th rowspan="2"> Respuesta </th>
    </tr>
    <tr>
        <th> A </th>
        <th> B </th>
        <th> C </th>
    </tr>
    
   </thead>
 
    <tbody>
    <tr>
      <td> 1 </td> <td> - </td> <td> - </td> <td> - </td> <td> y<sub>1</sub> </td>
    </tr>
    <tr>
      <td> 2 </td> <td> + </td> <td> - </td> <td> - </td> <td> <i>y<sub>2</sub></i> </td>
    </tr>
    <tr>  
      <td> 3 </td> <td> - </td> <td> + </td> <td> - </td> <td> <i>y<sub>3</sub></i> </td>
    </tr> 
    <tr>
      <td> 4 </td> <td> + </td> <td> + </td> <td> - </td> <td> <i>y<sub>4</sub></i> </td>
    </tr>  
    <tr>
      <td> 5 </td> <td> - </td> <td> - </td> <td> + </td> <td> <i>y<sub>5</sub></i> </td>
    </tr>  
    <tr>
      <td> 6 </td> <td> + </td> <td> - </td> <td> + </td> <td> <i>y<sub>6</sub></i> </td>
    </tr>  
    <tr>
      <td> 7 </td> <td> - </td> <td> + </td> <td> + </td> <td> <i>y<sub>7</sub></i> </td>
    </tr>
    <tr>
      <td> 8 </td> <td> + </td> <td> + </td> <td> + </td> <td> <i>y<sub>8</sub></i> </td>
    </tr>
  </tbody>
</table>
</div>
```
Pero realizar los experimentos en este orden tiene el inconveniente de que, si la respuesta tiende a aumentar o a disminuir a medida que se van realizando —ya sea por razones vinculadas al sistema de medida, a la materia prima, a la maquinaria o a lo que sea—, como los efectos principales se calculan haciendo el promedio de respuestas con el factor a nivel + menos el promedio con el factor a nivel –, el efecto principal del factor situado en la última columna (el C en el caso de un $2^3$) será el promedio de la mitad de experimentos realizados al final menos el promedio de la mitad de los realizados al principio. Al hacerlo de esta forma, la influencia del orden puede llevarnos a conclusiones equivocadas. Para evitar este tipo de situaciones, aleatorizamos el orden de realización de los experimentos y, si el orden tuviera alguna influencia, esperamos que esta se difumine entre todos los efectos sin concentrarse en ninguno de forma especial.

Planteada la razón de la aleatorización, surge la pregunta de qué ocurre si al aleatorizar el orden obtenido resulta ser el estándar. La respuesta es polémica. Vamos a comentarla bajo dos puntos de vista.

Algunas personas (les llamaremos “académicos”) consideran que el orden estándar es un orden como cualquier otro y no debería haber ninguna razón para rechazarlo. Si se tienen razones para sospechar que el orden afecta a la respuesta, lo que hay que hacer es bloquear el experimento y/o tomar las medidas adecuadas para que esa influencia no se presente. Además, esa influencia puede seguir cualquier patrón y, por tanto, tampoco está justificado temerle más a unos (tendencias crecientes o decrecientes) que a otros.

Otras personas (les llamaremos “prácticos”) opinan que si al aleatorizar sale el orden estándar lo mejor es volver a realizar la aleatorización. Porque aunque es verdad que la tendencia vinculada al orden puede ser de cualquier tipo, en el caso de que exista es más razonable considerar que sea monótona creciente o decreciente y en ese caso el orden estándar sale especialmente perjudicado. Además, es difícil explicar que el denostado orden estándar para realizar la experimentación es el que finalmente hay que llevar a cabo. Consuela saber que las probabilidades de que esto ocurra son pocas. Exactamente 1 entre 40.320 en un diseño $2^3$ y del orden de 1 entre 21 billones en un $2^4$.

Quizá en esta polémica conviene tener presente que la palabra “aleatorizar” se utiliza en estadística con dos significados distintos. Una cosa es aleatorizar la selección de una muestra que se va a considerar aleatoria, en cuyo caso esta es una condición crítica y hay que andarse con cuidado con los relajamientos, y otra cosa es aleatorizar el orden de realización de los experimentos. Aunque la palabra es la misma (quizá la más sacralizada de las que usamos en estadística) en el último caso se trata de una práctica del tipo “curarse en salud” de forma que su significado e implicaciones son distintas.
