# 8.4 ¿Cuál es la mejor estrategia para que me toque la lotería? {.unnumbered #loteria}

Si nos referimos sólo a juegos de azar, esos que se basan en la extracción de bolas de un bombo, esta pregunta no tiene respuesta, ya que no existe tal estrategia. Y es una lástima, porque a muchos les habrá parecido que esta era la pregunta más interesante del libro.

Pero, para no hacer esta respuesta demasiado corta, haremos algunas consideraciones sobre los sorteos en que se compra un boleto con un número y sobre aquellos en los que se elige una combinación de 6 entre los números del 1 al 49, o similares.

#### Boleto de lotería con un número

Supongamos que los números disponibles son del 0 al 99.999 y que el número premiado se elige al azar. Es evidente que, si todos tienen la misma probabilidad de salir, aquí no hay táctica que valga. Sin embargo, existen algunas falacias bastante extendidas que podemos comentar. Por ejemplo:

-   *Si se compra en determinados lugares (ciudades, puntos de venta), es más fácil que toque que si se compra en otros*. Los que mantienen esta postura la avalan con datos: en ese lugar que ellos dicen que da más premios, efectivamente en los últimos años ha dado muchos más que en ese otro donde es muy difícil que toque. La clave está en distinguir el número de premios de la probabilidad de que toque. El número de premios que caen en un lugar depende del número de boletos que se han vendido. Por eso, a la larga, tocan más premios en las ciudades grandes que en las pequeñas, pero esto no implica que tengamos más posibilidades de que nos toque si compramos el número en una ciudad grande. Las probabilidades son exactamente las mismas. Respecto a los puntos de venta, si en uno de ellos toca algún premio importante y se crea el clima de opinión de que allí es más fácil que toque, la gente irá más a comprar a ese lugar y, al venderse más, efectivamente aumenta la probabilidad de toque, aunque para el que compra la probabilidad no cambia en absoluto, tanto si lo compra allí como en cualquier otro lugar.

-   *Hay números "feos" que no hay que comprar porque nunca tocan*. Si a alguien le ofrecen el número 01010 es posible que no lo quiera, porque este es un número raro y le parecerá muy difícil que toque. Preferirá el 34.278, que es mucho más normal. Después resulta que toca un número como el 47.121, lo cual confirma la teoría de que los números que salen son normales, aunque, lamentablemente, no el "normal" que habíamos comprado. ¿Por qué tocan muy pocas veces los números raros? Pues simplemente porque números raros hay pocos (ver al final). Visto de otra forma: ¿por qué es más probable que toque fuera del intervalo 30.000–35.000 que dentro? Pues simplemente porque fuera hay más números que dentro, pero esto no hace que menospreciemos los números dentro de ese intervalo. Lo mismo ocurre con los números raros.

**Consejos**: Si compra lotería hágalo cerca de su casa o donde le pille más a mano. Se ahorrará tiempo, gastos de desplazamiento y quizá el disgusto de comprobar que ha tocado en el punto de venta de su calle y usted lo fue a comprar a otra ciudad. Y no rechace los números raros, especialmente si los ha visto y se va a acordar del número.

#### Elegir 6 números del 1 al 49 (o similar)

Este es un juego muy popular en todo el mundo. Se conoce con diversos nombres como Lotería primitiva, Lotto, Loto 6/49, etc. Hay premio a partir de 3 aciertos. Las probabilidades de acertar son (ver al final):

```{=html}
<div class="tabla-wrapper">
<table class="tabla-muestras">
  <thead>
    <tr>
      <th style="text-align:left;">Número de aciertos</th>
      <th style="text-align:left;">Probabilidad</th>
    </tr>
  </thead>

  <tbody>
    <tr style="text-align:left;"> <td style="text-align:left;">3</td> <td style="text-align:left;">1 en 56</td>  </tr>
    <tr> <td>4</td> <td>1 en 1032</td>  </tr>
    <tr> <td>5</td> <td>1 en 55.491</td>  </tr>
    <tr> <td>5 + Complementario</td> <td>1 en 2.330.636</td>  </tr>
   <tr style="border-bottom: 1px solid #000;">
         <td>6</td> <td>1 en 13.983.816</td> </tr>
  </tbody>
</table>
</div>
```
Algunas creencias sin fundamento:

-   *Hay que apostar a los números que han salido menos, ya que como la probabilidad es la misma para todos y a la larga su frecuencia de aparición tiende a igualarse, será más probable que salgan los que menos han salido*. Es verdad que, a la larga, las frecuencias de aparición tienden a igualarse, de la misma forma que si lanzamos muchas veces una moneda al aire, cuantas más veces la lancemos, más cerca estará del 50 % la proporción de caras y cruces. Pero esto no quiere decir que después de 5 caras sea más probable que salga una cruz, la probabilidad siempre es constante para ambos resultados, y de la misma forma ocurre con los números que salen en este tipo de sorteos. Los bombos no tienen memoria y no saben lo que ha salido antes. Ni memoria ni sentimientos de justicia o igualdad. Simplemente, las probabilidades son las mismas en todos los sorteos, independientemente de lo que haya salido en los sorteos anteriores.

-   *Hay que apostar por los números que más salen, puesto que esos, por las razones que sean, son los que han demostrado tener más probabilidad de salir*. Lo verdaderamente sorprendente sería que todos los números hubieran salido exactamente el mismo número de veces. Lo normal es que, por azar, unos hayan salido más y otros menos. Pero no hay ninguna razón para pensar que los que han salido más hasta ahora vayan a seguir saliendo más. Por la misma razón que antes, las probabilidades son idénticas en cada sorteo.

-   *Existen estrategias que, con ayuda de un ordenador, permiten elaborar combinaciones múltiples que aumentan las probabilidades de ganar*. Es posible incluso garantizar que se tendrá algún premio si se realiza un cierto número de apuestas adecuadamente seleccionadas. Pero si por ganar se entiende tener beneficios (premio -- coste del juego), la tendencia es que cuanto más se juega, más se pierde, con independencia de la estrategia que se siga. En otro tipo de apuestas, en las que el resultado no depende sólo del azar, como las quinielas de fútbol, sí pueden existir estrategias para aumentar la probabilidad de beneficio.

**Consejos**: Aunque la probabilidad de que una combinación toque es la misma para todas ellas, cuanto mayor sea la cantidad a repartir, más dinero ganará si le toca, por lo que tiene más emoción jugar cuando hay mucho dinero acumulado de otras semanas en las que no hubo ningún acertante. Por otra parte, como el premio se reparte entre los acertantes, parece una buena idea apostar por una combinación rara, ya que tiene las mismas probabilidades de salir que cualquier otra y, si nos toca, probablemente seremos los únicos acertantes y cobraremos más dinero. Lo que es una combinación rara no está muy claro y seguramente también depende de la disposición de los números en el boleto. En fin, marque los números que se le antojen o, todavía más cómodo, que los marque la máquina, y espere a ver si ha habido suerte, con la seguridad de que nadie ha usado una estrategia mejor que la suya.

$$ \bullet \;\;\;\;\; \bullet \;\;\;\;\; \bullet $$

<small>

**Números raros**: si por raro entendemos un número con sólo 1 ó 2 cifras distintas (por ejemplo, el 22.222 o el 22.552), números en los que aparece sólo una cifra tenemos 10 (00.000, 11.111, $\dotsi$, 99.999) y números en los que aparecen 2 cifras, si tenemos 4 iguales y una distinta, son: $10 \cdot 9 \cdot 5$ (10 posibilidades para el primero, 9 para el segundo y 5 formas posibles de ordenarlos). Si tenemos 3 iguales por un lado y 2 iguales por otro: $10 \cdot 9 \cdot \frac{5!}{2! \cdot 3!}=900$. Es decir que con este criterio, números raros hay 10 + 450 + 900 = 1.360 entre 100.000.

**Probabilidad de acertar en lotería 6/49** Para calcular estas probabilidades podemos usar la regla de casos favorables partido por casos posibles. Los casos posibles, es decir, las formas de elegir 6 números de un conjunto de 49 son las combinaciones de 49 tomados de 6 en 6, que notamos $\binom{49}{6}$. Los casos favorables para acertar 3 es el producto de los casos en que se pueden elegir los 3 que se aciertan de entre los 6 premiados $\binom{6}{3}$ por los casos en que se pueden elegir los 3 que no se aciertan de entre los 43 no premiados $\binom{43}{3}$. El resultado para la probabilidad de acertar 3 es: $\binom{6}{3} \cdot \binom{43}{3} / \binom{49}{6}$ = 0,0176504. Análogamente, para 4 aciertos la probabilidad es $\binom{6}{4} \cdot \binom{43}{2} / \binom{49}{6}$ = 0,0009686. La probabilidad de acertar 5, sin el número complementario, es $\binom{6}{5} \cdot \binom{42}{1} / \binom{49}{6}$ = 0,0000180 (en el numerador aparece 42 porque el número no premiado se elige de entre los no premiados menos el complementario). La probabilidad de acertar 5 más el complementario es $\binom{6}{5} / \binom{49}{6}$= 0,0000004, ya que hay una sola forma de elegir el complementario. Y finalmente, la probabilidad de acertar los 6 es una entre todas las combinaciones posibles, es decir: $1 / \binom{49}{6}$ = 1 entre 14 millones, aproximadamente.

</small>
