# PRESENTACIÓN {.unnumbered}

Respondemos a preguntas que suelen surgir en un curso general de estadística. Se refieren tanto al contenido propio del curso como a cuestiones que aparecen habitualmente en discusiones sobre qué es la estadística, cuáles son sus dificultades y cuáles son sus aplicaciones.

Este libro es el resultado de nuestra experiencia en este ámbito y esperamos que sea útil a estudiantes, a profesores que se inician en la docencia y a personas interesadas en la estadística en general. Cualquier comentario o sugerencia será bienvenido.

<!-- <p style="font-size: 1.2em;"> -->
<!--   **Lista de preguntas**. -->
<!-- </p> -->

<!-- ### Lista de preguntas -->

Versión 4.0 (Marzo de 2026)

### Autores

::: poco-espacio
[Roberto Behar](https://die.udistrital.edu.co/comunidad/roberto_behar_gutierrez), profesor en la Universidad del Valle, en Cali, Colombia.

[Pere Grima](https://www-eio.upc.es/~grima/index.html), profesor en la Universitat Politècnica de Catalunya, en Barcelona, España
:::

### Libro impreso

Se puede comprar en [Amazon.es](https://amzn.eu/d/hGbwqAH "Amazon.es") o [Amazon.com](https://www.amazon.com/dp/B09SL18YRT "Comprar en Amazon.com"). Está impreso en color, encuadernado con tapa blanda e incluye prólogo, índices y referencias.

### Licencia

Se publica bajo una licencia Creative Commons: [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.es "Licencia Creative Commons").
