# LISTA DE PREGUNTAS {.unnumbered}

**1. Estadística: Lo que es y lo que no es**<br> [1.1 ¿La estadística es una parte de las matemáticas?](#Matematicas)<br> [1.2 ¿La estadística es una parte de las matemáticas?](#Probabilidad)<br> [1.3 ¿Qué es la estadística?](#QueEs) <br> [1.4 Qué es la ciencia de datos (o *Data Science*)](#DataScience)

**2. Estadística Descriptiva**<br> [2.1 ¿Para qué sirve la mediana si ya tenemos la media aritmética?](#Mediana) <br> [2.2 ¿Tiene alguna aplicación práctica la media geométrica?](#geometrica) <br> [2.3 ¿Por qué damos tanta importancia a la variabilidad?](#variabilidad) <br> [2.4 ¿Por qué en la fórmula de la varianza se utiliza el cuadrado en vez del módulo?](#cuadrado) <br> [2.5 ¿Por qué cuando se calcula la varianza de una muestra se divide por n-1?](#n-1) <br> [2.6 ¿Por qué la desviación típica es la medida típica de dispersión?](#tipica) <br> [2.7 ¿Cuál es la forma “correcta” de calcular los cuartiles?](#cuartiles) <br> [2.8 ¿De dónde sale el 1,5 utilizado para marcar las anomalías en un boxplot?](#anomalias) <br> [2.9 ¿Qué hay que hacer cuando nos encontramos con valores atípicos?](#atipicos) <br> [2.10 ¿Para qué sirve la curtosis?](#curtosis) <br> [2.11 ¿Qué gráfico debo usar para representar mis datos?](#graficosUsar) <br>[2.12 ¿Qué gráficos NO debo usar para representar mis datos?](#graficosNOusar) <br> [2.13. ¿Cuáles son los mejores programas para analizar datos gráficamente?](#software)

**3. Distribuciones de probabilidad** <br> [3.1 ¿Cómo se pasa de la frecuencia a la densidad de probabilidad?](#frecuencia) <br> [3.2 ¿Cómo se sabe qué distribución sigue una variable aleatoria?](#distribucion) <br> [3.3 ¿Por qué se dice que la media es una variable aleatoria?](#mediaAleatoria) <br> [3.4 ¿De dónde sale la fórmula de la distribución Normal?](#formulaNormal) <br> [3.5 ¿Por qué para la distribución Normal solo se necesita la tabla de la N(0; 1)?](#N01) <br> [3.6 ¿Por qué la probabilidad de tener mi estatura es igual a cero?](#estatura) <br> [3.7 ¿Existen variables con comportamiento contrario a la distribución Normal?](#contrarioNormal) <br> [3.8 ¿De dónde sale la fórmula de la distribución de Poisson?](#Poisson) <br> [3.9 ¿Cómo se relaciona la varianza muestral con la distribución Chi-cuadrado?](#Chi2) <br> [3.10. ¿Por qué no es lo mismo sumar k veces una variable aleatoria que multiplicarla por k?](#sumark)

**4. Muestreo y Estimación** <br> [4.1 ¿Por qué nos creemos los resultados de una muestra sabiendo que si tomáramos otra serían distintos?](#creemosMuestra) <br> [4.2 ¿De dónde sale la expresión del intervalo de confianza?](#IC) <br> [4.3 ¿Qué es el factor de corrección por población finita?](#factorCorreccion) <br> [4.4 ¿Cuántos elementos debe tener una muestra para que las conclusiones sean fiables?](#elementosMuestra) <br> [4.5 ¿Qué relación hay entre tamaño de muestra y tamaño de población?](#elementosMuestra) <br> [4.6 ¿Qué tipo de muestreo conviene elegir?](#tipoMuestreo) <br> [4.7 ¿Es lo mismo muestrea aleatoria que muestra representativa?](#aleatoria) <br> [4.8 ¿Por qué cuesta acertar en los sondeos electorales?](#sondeos) <br> [4.9 ¿Qué es un estimador de máxima verosimilitud?](#maximoverosimil)

**5. Contraste de hipótesis** <br> [5.1 ¿Qué es un contraste de hipótesis?] <br> [5.2 ¿Por qué es controvertido el uso del contraste de hipótesis?] <br> [5.3 ¿Cómo elegir la hipótesis alternativa que conviene plantear?] <br> [5.4 ¿Por qué se habla de “no rechazo” y no de “aceptación”?] <br> [5.5 ¿Cómo se sabe hacia qué lado hay que mirar el área de cola?] <br> [5.6 ¿A partir de qué p-valor se debe rechazar la hipótesis nula?] <br> [5.7 ¿Qué tipos de error se pueden cometer en un contraste de hipótesis?] <br> [5.8 ¿Es lo mismo diferencia significativa que diferencia importante?] <br> [5.9 ¿Es correcto multiplicar por dos el área de la cola en los test de igualdad de varianzas?]

**6. Diseño de experimentos** <br> [6.1 ¿Cómo que diseño de experimentos? ¿no es eso de física o de química?] <br> [6.2 ¿Por qué no se usa el test de la t-Student para comparar más de dos tratamientos?] <br> [6.3 ¿Por qué se llama Análisis de la Varianza si lo que se compara son medias?] <br> [6.4 ¿Por qué no hay que mover las variables una a una?] <br> [6.5 ¿Cómo es posible estudiar por separado el efecto de cada variable?] <br> [6.6 ¿Cómo se puede escribir una ecuación para la respuesta con los resultados de un diseño factorial?] <br> [6.7 ¿Qué es un diseño bloqueado?] <br> [6.8 ¿Por qué se suponen no significativas las interacciones de tres o más factores?] <br> [6.9 ¿Qué hacer si al aleatorizar aparece el orden estándar de la matriz de diseño?]

**7. Correlación y regresión** <br> [7.1 ¿Cómo se justifica la fórmula de la covarianza?] <br> [7.2 ¿De dónde sale la fórmula del coeficiente de correlación?] <br> [7.3 ¿Cómo se calculan los valores críticos del coeficiente de correlación?] <br> [7.4 ¿Sirven las tablas del coeficiente de correlación si X e Y no son Normales?] <br> [7.5 ¿Por qué se utiliza el método de los mínimos cuadrados?] <br> [7.6 ¿Por qué los coeficientes de una ecuación de regresión son variables aleatorias?] <br> [7.7 ¿Cómo se interpreta el valor de R2] <br> [7.8 ¿Por qué cuando se ajusta la recta por el origen no se debe usar R2] <br> [7.9 ¿Por qué hace falta el valor de R2 -ajustado si ya tenemos el de R2?] <br> [7.10 ¿Se pueden usar variables cualitativas en ecuaciones de regresión?] <br> 7.11 [¿Por qué las variables que se incluyen en el modelo no necesariamente son las más correlacionadas con la respuesta?]

**8. Miscelánea** <br> [8.1 Cuando se habla de transformación logarítmica ¿se refiere al logaritmo decimal o al neperiano?] <br> [8.2 ¿Debe decirse “Teorema central del límite” o “Teorema del límite central”?] <br> [8.3 ¿Qué significan los llamados “grados de libertad”?] <br>[ 8.4 ¿Cuál es la mejor estrategia para que me toque la lotería?] <br> [8.5 Acaba de salir 5 veces el rojo ¿debo apostar al negro?] <br> [8.6 ¿Cómo se dice? ¿Qué significa?]
