# Prólogo a la primera edición {.unnumbered}

Muchos de los que alguna vez hemos sido estudiantes de un curso de Estadística,  recordamos momentos en los que intentábamos entender, no siempre con éxito, las razones por las cuales había que hacer las cosas de una determinada manera.  ¿Por qué dividir por n-1 al calcular la desviación estándar? ¿Por qué no dividir por el número total de datos? El tiempo disponible en los cursos no permite explicarlo todo y en ocasiones el profesor, en su intento por dar una explicación al estudiante que pregunta, responde usando términos como “grados de libertad”  o “estimador insesgado”, lo cual puede generar más dudas de las que aclara.

Por otra parte, a través de nuestra experiencia ayudando a profesionales de la Medicina, la Administración o la Ingeniería en el uso de métodos estadísticos, hemos comprobado que los conceptos o las técnicas con que se trabaja no siempre están del todo claras. ¿Cómo hay que interpretar el p-valor que da el listado del ordenador? ¿Es lo mismo diferencia significativa que diferencia importante? Esta falta de seguridad en su manejo hace que muchas veces se evite hacer uso de todas las posibilidades que brinda la estadística, con lo que se pierde la oportunidad de obtener una información que puede resultar muy útil para la toma de decisiones.

También en un ámbito no estrictamente profesional existen muchas dudas “populares” en torno a la Estadística: ¿cómo es que con una muestra de 2.000 personas puede conocerse razonablemente bien la opinión de un país de 40 millones de habitantes?, o lo que es todavía más sorprendente, ¿cómo es que esas 2.000 personas también serían suficientes para una población de 100 millones? Y ligada con estas, si la Estadística es tan potente, ¿por qué cuesta tanto acertar en los sondeos electorales?

Este texto pretende dar respuesta a muchas de estas preguntas y nuestra intención es que sea útil tanto a los estudiantes de los cursos de estadística que se imparten en la universidad, como a los profesionales que están interesados en refrescar sus ideas o aclarar dudas concretas, y también a todas aquellas personas interesadas en esta disciplina que quieran resolver algunas de sus dudas.

Sin ser exhaustivos, pues siempre es posible aumentar la lista con nuevas preguntas, hemos tratado de cubrir  un amplio espectro, tratando dudas en estadística descriptiva,  distribuciones de probabilidad, estimación, contraste de hipótesis, comparación de poblaciones,  correlación y regresión, diseño de experimentos,  estudios de capacidad y control de procesos y un apartado para dudas varias, como las relacionadas con los grados de libertad y el teorema central del límite, entre otras.

Muchas preguntas tienen un carácter general e introductorio y son “aptas para todos los públicos”, pero otras tratan sobre temas específicos en el contexto de las ecuaciones de regresión, el diseño de experimentos o el control estadístico de procesos. En este último caso se requiere un cierto nivel de conocimientos sobre el tema, aunque si la pregunta despierta interés, seguramente ya se sabe lo suficiente para entender la respuesta. En todos los casos se ha intentado usar un lenguaje coloquial, recurriendo a la intuición y apoyándose en la metáfora, pero procurando que no haya pérdida en el rigor.

Se ha intentado también que cada respuesta sea lo más autocontenida posible, es decir, lo suficientemente completa, para que no requiera de otras para su adecuada  comprensión.  De todas maneras, en cada uno de los temas que se tratan, se han colocado las dudas y sus respuestas en el orden que consideramos más efectivo, de tal manera que un lector que desee leer todas las preguntas de un apartado en forma secuencial vaya ganando elementos para comprender mejor la siguiente.

Dejando claro que cualquier falta en la virtud de este trabajo es de exclusiva responsabilidad de los autores,  deseamos poner de manifiesto nuestro agradecimiento  a todos nuestros compañeros en las tareas docentes, seguramente la mejor fuente de información que hemos tenido. Lluís Marco, de la Universitat Politècnica de Catalunya y Guillermo de León, de la Universidad Veracruzana nos sugirieron algunas de las preguntas que se incorporan y también ideas y posibles enfoques para muchas respuestas, además de leer los originales y sugerir numerosas mejoras. Rafael Antonio Klinger y Eloina Mesa, de la Universidad del Valle, también leyeron los originales y realizaron muchas sugerencias que han mejorado notablemente la claridad de las respuestas. 

Deseamos agradecer también a la Agencia Española de Coo-peración Internacional (AECI) y a nuestras Universidades, la Universidad del Valle y la Universitat Politècnica de Catalunya, las ayudas y facilidades obtenidas para la realización de este trabajo.

Muy probablemente, no podremos evitar la frustración de algunos de nuestros lectores al buscar en vano alguna duda que no fue tratada aquí, o al no quedar del todo satisfechos con alguna respuesta. Nuestra aspiración es poder recoger todas las sugerencias y apreciaciones que nos permitan realizar un proceso mejora continua de nuestro trabajo, por lo que agradeceremos todos los comentarios y sugerencias que nos hagan llegar a través de la página web: www.55RespuestasEstadistica.com\footnote{Nota en la edición actual: Esta página web ya no existe}
\\
\\
\noindent Barcelona y Santiago de Cali, Mayo de 2004
